# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_summary', models.CharField(max_length=500, verbose_name='需求概要')),
                ('req_des', models.CharField(max_length=1000, verbose_name='需求描述')),
                ('req_raise_date', models.DateField(verbose_name='提出时间')),
                ('req_raise_user', models.CharField(max_length=100, verbose_name='提出人')),
                ('req_raise_dep', models.CharField(max_length=100, verbose_name='提出部门')),
                ('req_doc_finish_date', models.DateField(blank=True, null=True, verbose_name='文档完成时间')),
                ('req_status', models.CharField(max_length=100, verbose_name='当前状态')),
                ('req_developer', models.CharField(blank=True, max_length=100, null=True, verbose_name='开发人员')),
                ('req_doc_link', models.CharField(blank=True, max_length=300, null=True, verbose_name='文档链接')),
            ],
        ),
    ]
