# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='req_expect_date',
            field=models.DateField(default='2000-01-01', verbose_name='期望完成日期'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='req_priority',
            field=models.CharField(default='中', max_length=100, verbose_name='优先级'),
        ),
    ]
