# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0002_auto_20170913_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'verbose_name': '需求', 'verbose_name_plural': '需求s'},
        ),
        migrations.AddField(
            model_name='requirement',
            name='req_uccode',
            field=models.CharField(default='001', max_length=100, verbose_name='用例编号'),
        ),
    ]
