# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0003_auto_20170913_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='req_uccode',
            field=models.CharField(max_length=100, unique=True, verbose_name='用例编号'),
        ),
    ]
